[package]
name = 'jsdotlua/shared'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
