[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.26.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.15.1" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
luau-lsp = { github = "johnnymorganz/luau-lsp", version = "=1.23.0"}
darklua = { github = "seaofvoices/darklua", version = "=0.12.1" }
lune = { github = "filiptibell/lune", version = "0.7.11" }
