[workspace]
version = "17.0.2"
members = ["modules/*"]
authors = [
	"Paul Doyle <pdoyle@roblox.com>",
	"Matt Hargett <mhargett@roblox.com>",
	"Max Mines <mmines@roblox.com>",
	"Carlo Conte <cconte@roblox.com>",
	"Henry Allen <hallen@roblox.com>",
	"Olivier Trepanier <otrepanier@roblox.com>",
	"Hugh Collins <hcollins@roblox.com>"
]

[workspace.dependencies]
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
Jest = "github.com/roblox/jest-roblox@3"
JestGlobals = "github.com/roblox/jest-roblox@3"
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
