[package]
name = 'jsdotlua/react-reconciler'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.2'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Promise = 'evaera/promise@4.0.0'
React = 'jsdotlua/react@17.0.2'
Scheduler = 'jsdotlua/scheduler@17.0.2'
Shared = 'jsdotlua/shared@17.0.2'
