[package]
name = "ReactDevtoolsExtensions"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
Shared = { path = "../shared" }
React = { path = "../react" }
ReactDevtoolsShared = { path = "../react-devtools-shared" }
ReactRoblox = { path = "../react-roblox" }

[dev_dependencies]
JestGlobals ={ workspace = true }
# FIXME: Version 0.2.4 breaks the test "can connect to a Roact tree and inspect
# its children and child branch nodes" in devtools-integration.roblox.spec.lua
DeveloperTools = "github.com/Roblox/developer-tools@=0.2.3"
ReactTestRenderer = { path = "../react-test-renderer" }