[package]
name = 'jsdotlua/react-devtools'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.2'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ReactDevtoolsCore = 'jsdotlua/react-devtools-core@17.0.2'
