[package]
name = "ReactShallowRenderer"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
React = { path = "../react" }
ReactIs = { path = "../react-is" }
Shared = { path = "../shared" }

[dev_dependencies]
JestGlobals = { workspace = true }
RobloxJest = { path = "../roblox-jest" }
